server:
  port: 8080
  servlet:
    context-path: /lab-dev-extreme-archetype
  error:
    include-message: always
spring:
  datasource:
    url: DEC(jdbc:oracle:thin:@localhost:1521:xe)
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: DEC(dbname)
    password: DEC(dbpassword)
    sqlScriptEncoding: UTF-8
    initialization-mode: always
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
logging:
  level:
    br:
      jus: INFO
    org:
      hibernate:
        SQL: INFO
      springframework:
        jdbc:
          core:
            JdbcTemplate: INFO
keycloak:
  auth-server-url: https://prod-k8s.tre-pa.jus.br/auth
  bearer-only: true
  config:
    base-url: https://prod-k8s.tre-pa.jus.br/lab-dev-extreme-archetype/
    valid-redirect-url: https://prod-k8s.tre-pa.jus.br/lab-dev-extreme-archetype/*
    backend-id: lab-dev-extreme-archetype-backend
    frontend-id: lab-dev-extreme-archetype-frontend
  credentials:
    secret: DEC(cc4e02ba-ce2d-4f30-8155-c5a560b103eb)
  realm: TRE-PA
  resource: lab-dev-extreme-archetype-backend
  ssl-required: external
  use-resource-role-mappings: true
info:
  app:
    name: "@projectname@"
management:
  server:
    port: 9090
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    web:
      exposure:
        include: "health,info,prometheus,auditevents"