server:
  port: 8080
  servlet:
    context-path: /lab-dev-extreme-archetype
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: labdevextremearchetype
    password: labdevextremearchetype
    sqlScriptEncoding: UTF-8
    initialization-mode: always
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
logging:
  level:
    br:
      jus: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
keycloak:
  auth-server-url: http://localhost:8085/auth
  bearer-only: true
  config:
    base-url: http://localhost:4200/
    valid-redirect-url: http://localhost:4200/*
    backend-id: lab-dev-extreme-archetype-backend
    frontend-id: lab-dev-extreme-archetype-frontend
  credentials:
    secret: f541e548-ff50-4c97-928d-f296fcd7be9c
  realm: TRE-PA
  resource: lab-dev-extreme-archetype-backend
  ssl-required: external
  use-resource-role-mappings: true
info:
  app:
    name: "@projectname@"
management:
  server:
    port: 9090
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    web:
      exposure:
        include: "health,info,prometheus,auditevents"