---

apiVersion: v1
kind: Service
metadata:
  name: lab-dev-extreme-archetype 
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: lab-dev-extreme-archetype
  type: ClusterIP

...
