apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-dev-extreme-archetype
spec:
  template:
    spec:
      containers:
        - name: lab-dev-extreme-archetype
          env:
            - name: spring.profiles.active
              value: dev
